name: ican
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_pagination: ^3.0.0
  infinite_listview: ^1.1.0
  getwidget: ^3.1.1
  image_picker: ^0.8.7+1
  xid: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - images/ICANicon.png
    - images/Tyler.png
    - images/taz.jpg

fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400